### ISSUE TITLE
Invariant Violation: 9

### ISSUE THREAD

**Issue by TAnas0** [apollographql/invariant-packages#13]
Hello,

I am having an issue with Apollo (used in a VueJS project). The following error message is displayed where I am referred to this repository:

```
Invariant Violation: Invariant Violation: 9 (see https://github.com/apollographql/invariant-packages)
    at new e (https://alpha.loyaly.app/js/chunk-vendors.228b37e2.js:34:16801)
    at https://alpha.loyaly.app/js/chunk-vendors.228b37e2.js:57:14337
    .....
    .....
```

Googling only led me to the same error message, but with a different code. I couldn't manage to find these number code documented or understand what the code `9` meant.

In my case, I am using a mutation with variables for the first time on this project, so there is a high chance that my code is faulty

Hope somebody can help

**Comment by TAnas0** [comment]
I have resolved my particular issue by refactoring. I was making the mutation in a callback and it was somehow indirectly causing this specific error.

Also, I found out that I have `ts-invariant` as a dependency of [vue-cli-plugin-apollo](https://github.com/Akryum/vue-cli-plugin-apollo). So they are responsible of defining the error codes in question?

Output of `yarn why ts-invariant`:
```
=> Found "graphql-anywhere#ts-invariant@0.3.3"
info This module exists because "_project_#@loyaly#app#vue-cli-plugin-apollo#apollo-link-state#graphql-anywhere" depends on it.
```

**Comment by PowerKiKi** [comment]
The error code is generated by this lib, incremental starting from 1, in a generic and automated way. But the error itself is thrown by your application (or one of your dependencies). It is not a bug in this lib.

To know what the error code means for your specific app, you'll have to check the unminified bundle of your app. 

Also see https://github.com/apollographql/invariant-packages#error-codes
