### ISSUE TITLE
Usage of const keyword in ts-invariant package

### ISSUE THREAD

**Issue by hamlim** [apollographql/invariant-packages#179]
Hello 👋

We recently noticed that the `ts-invariant` package seems to be shipping code with `const` references within it which can break on browsers that don't support those es6 features (e.g. IE).

Would it be possible to ship an es5 compatible version of this package? We're currently relying on this package via a few Apollo dependencies.

**Comment by shevchenkonik** [comment]
Hey there! 

I've described my issue [here](https://github.com/apollographql/apollo-client/pull/8720#issuecomment-912480707) but it is similar to yours.

**Comment by benjamn** [comment]
This should be fixed in `ts-invariant@0.9.2`, thanks to @shevchenkonik's PR #200.
