### ISSUE TITLE
Instructions are way too vague

### ISSUE THREAD

**Issue by dobesv** [apollographql/invariant-packages#18]
> Since the full development version of the error is colocated with the production one in code that has been transformed by rollup-plugin-invariant, it should be relatively easy to determine the nature of the error by looking for the given error code in the unminified bundle.

Although it says "it should be relatively easy" I honestly have no idea what I'm supposed to be looking for.  Maybe an example would help?

**Comment by penx** [comment]
Same here. I've not used this module personally, a team member has. I see this error in the CI logs and it directs me here. Not sure where to begin after reading that. Should the readme be linking to a certain file within the project?

**Comment by dobesv** [comment]
It looks like the idea is to grep for `_tsInvarient.invariant` or `InvariantError`, something like this:

```
# If you're using ES modules (probably the case if you're using webpack, but I'm not 100% sure)
$ grep -ir "invariant.*17)" node_modules/apollo-client/bundle.esm.js
            process.env.NODE_ENV === "production" ? invariant(foundObserveableQuery, 17) : invariant(foundObserveableQuery, "ObservableQuery with this id doesn't exist: " + queryIdOrObservable);
# If you're using commonjs bundle (e.g. in node.js)
$ grep -ir "invariant.*17)" node_modules/apollo-client/bundle.cjs.js
      process.env.NODE_ENV === "production" ? (0, _tsInvariant.invariant)(foundObserveableQuery, 17) : (0, _tsInvariant.invariant)(foundObserveableQuery, "ObservableQuery with this id doesn't exist: " + queryIdOrObservable);
```

**Comment by balazsorban44** [comment]
https://github.com/apollographql/apollo-client/pull/6665 This should help from now on. If @dobesv  agrees, this could be closed.
