### ISSUE TITLE
Invariant Violation: Invariant Violation: 44

### ISSUE THREAD

**Issue by balazsorban44** [apollographql/invariant-packages#19]
Sent to here with the following:
Invariant Violation: Invariant Violation: 44 (see https://github.com/apollographql/invariant-packages)

I have not a single clue what I am supposed to do. I have seen folks using `grep` like:
```
grep -r "InvariantError(" node_modules/**/bundle.cjs.js
```
or
```
grep -r "InvariantError(" node_modules/**/bundle.esm.js
```

None of those have a 44.

What does that mean? How should I debug this?

using:
```
"@apollo/client": "^3.0.0-rc.2",
"@apollo/link-context": "^2.0.0-beta.3",
```

not sure what else is relevant, cause I don't know the error's origin.

Could someone help with this?

**UPDATE:** I resolved the issue in my code. The problem was that I used `useQuery`/`useMutation` hooks of `@apollo/client` outside of `ApolloProvider`.

*This does resolves this issue itself, the dev experience was somewhat cumbersome, and my solution was to hunt down the breaking commit, rather than getting a clear message of the possible error.*

**Comment by cwshevlin** [comment]
I'm currently trying to track down an Invariant Violation: 8 and having the same experience manually searching the code. The text in parenthesis says to visit this repository, but there is not a clear next step once you get here.

**Comment by ifndefdeadmau5** [comment]
For me it happened when I have `client.readQuery` in my code but there's no such a cached query result in my store beforehand

**Comment by chrise86** [comment]
@cwshevlin did you manage to resolve your issue? I'm facing the same thing now (`Invariant Violation: 8`).

**Comment by balazsorban44** [comment]
https://github.com/apollographql/apollo-client/pull/6665 This should be of help to newcomers.

**Comment by sandorvasas** [comment]
So, maybe apollo should just print the messages themselves into the error, instead of having developers go through jungles of forums to find what it means?
