### ISSUE TITLE
How to skip invariant in webpack?

### ISSUE THREAD

**Issue by eternalmatt** [apollographql/invariant-packages#23]
Hello, I found this module attempting to violate my Content Security Policy after tracking it down in my webpack bundle line 1, column 554,074 as it were.  After finding that actual column, then grepping my node_modules for `Function('stub'`, I am greeted with the lovely code comment here: https://github.com/apollographql/invariant-packages/blob/master/packages/ts-invariant/src/invariant.ts#L54-L57

As I would very much like to not include "unsafe-eval" and also not post back csp-violations to my server, how can I disable this functionality in my production webpack build?

I build with Angular CLI --prod so the minified code looks like this: 
```
var c={env:{}};if("object"==typeof process)c=process;else try{Function("stub","process = stub")(c)}catch(l){}}
```

**Comment by benjamn** [comment]
@eternalmatt Starting in `ts-invariant@0.6.0`, the `Function` constructor is no longer used (even as a fallback) to obtain a reference to the global object. I will update `@apollo/client` to use version 0.6.0 of this package today/soon.

**Comment by eternalmatt** [comment]
Thanks!
