### ISSUE TITLE
ts-invariant TS config missing "node" type

### ISSUE THREAD

**Issue by fjcaetano** [apollographql/invariant-packages#6]
Typescript fails for projects that don't define "node" in their TS config `types` attribute. To simply fix this issue, `ts-invariant` should add that requirement to its own TS config file. 

However, it seems to me `ts-invariant` shouldn't require "node" at all. The library is mostly being used by Apollo, which can be installed in React Native and that creates a lot of type conflicts since both `node` and `react-native` types define a lot of duplicate definitions. The `node` type is only being used by `ts-invariant` for the `processStub: NodeJS.Process` type, so it seems a bit exaggerated to require a massive type definition such as `node` for a single variable. Perhaps there's a better way of defining `processStub`'s type so that importing `node` definitions become optional.

**Comment by derolf** [comment]
I also think the dependency to node should be removed because this packed pollutes the entire dependent project with node types.
