### ISSUE TITLE
Does anyone know where the reference to @types/node is coming from?

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/invariant-packages#74]
In the latest published version of this package of 0.6.0: https://registry.npmjs.com/ts-invariant/-/ts-invariant-0.6.0.tgz

In `lib/invariant.d.ts`, you can see this right at the top:
```ts
/// <reference types="node" />
```

Though how is it getting there? I don't see it anywhere in the sources within this repo.

This is causing the node types to leak into our projects based on this issue:
microsoft/TypeScript#31148 (comment)

I've also already commented on this package here:
apollographql/apollo-client#7734

Though I'm confused and would like some clarification.

**Comment by jimisaacs** [comment]
Related issue: https://github.com/apollographql/subscriptions-transport-ws/issues/851

**Comment by Venryx** [comment]
I have the same issue. It's apparently stemming from the `processStub` variable in [ts-invariant/src/invariant.ts](ts-invariant/lib/invariant.d.ts).

More info here: https://github.com/apollographql/apollo-client/issues/7734#issuecomment-782586343
